name: medeasee
description: A new Flutter project

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ UI & UX
  cupertino_icons: ^1.0.2
  pinput: ^3.0.1
  circular_reveal_animation: ^2.0.1
  provider: ^6.1.1
  intl: ^0.18.1
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  visibility_detector: ^0.4.0+2
  photo_view: ^0.14.0
  video_player: ^2.7.2

  # ✅ Media & File Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1

  # ✅ Firebase & Cloud
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.7.6
  firebase_dynamic_links: ^5.4.8

  # ✅ Local Storage & Notifications
  shared_preferences: ^2.2.2
  flutter_local_notifications: 16.2.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  local_auth: ^2.1.6 # ✅ Added for fingerprint/PIN auth

  # ✅ Networking & Sharing
  http: ^0.13.6
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  android_intent_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/Images/medicine 1.png
    - assets/Images/doc.png
    - assets/Images/ambu.png
    - assets/Images/splash_photo.png
    - assets/Images/landing_logo.png
    - assets/Images/google.png
    - assets/Images/reminder-1.png
    - assets/Images/reminder-2.png
    - assets/Images/once_daily.png
    - assets/Images/health_record.png
    - assets/Images/bill_image.png
    - assets/Images/test_image.png
    - assets/Images/prescription_image.png
    - assets/Images/folder_image.png
    - assets/Images/camera_image.png
    - assets/Images/gallery_image.png
    - assets/Images/file_image.png
    - assets/Images/google_drive.png
    - assets/Images/connect.png
    - assets/Images/invite.png
    - assets/Images/share.png
    - assets/Images/logo_photo.png
    - assets/Images/family_landing.png

    # Videos
    - assets/videos/reminder-3.mp4
    - assets/videos/twice_daily.mp4
    - assets/videos/multiple_times.mp4
    - assets/videos/specific_times.mp4
    - assets/videos/cyclic_extension.mp4
    - assets/videos/inventory_reminder.mp4
    - assets/videos/inventory_2.mp4
    - assets/videos/carebuddy_profile.mp4
    - assets/videos/connect_manually.mp4
    - assets/videos/invite_page.mp4
    - assets/videos/page_1.mp4
    - assets/videos/share_link.mp4
    - assets/videos/logo_video.mp4

    # Icons
    - assets/icons/reminder.png
    - assets/icons/reminder_selected.png
    - assets/icons/medvault.png
    - assets/icons/medvault_selected.png
    - assets/icons/sos.png
    - assets/icons/sos_selected.png
    - assets/icons/family.png
    - assets/icons/family_selected.png
    - assets/icons/account.png
    - assets/icons/account_selected.png
    - assets/icons/tablet.png
    - assets/icons/notification.png
    - assets/icons/info.png
    - assets/icons/data.png
    - assets/icons/account_pin.png
    - assets/icons/contacts_fill.png
    - assets/icons/email_fill.png
    - assets/icons/phone_fill.png
    - assets/icons/acc.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
