// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9u0mgqCxHOYY159QkbHhKNj_j8T64jSc',
    appId: '1:71986374792:android:7b591e864a98b38034973d',
    messagingSenderId: '71986374792',
    projectId: 'medease-79081',
    storageBucket: 'medease-79081.appspot.com', // ✅ FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrjjIZ-bhSIMCj57mkYeGIoa-1kWt76-c',
    appId: '1:71986374792:ios:3b8bf4576399cac734973d',
    messagingSenderId: '71986374792',
    projectId: 'medease-79081',
    storageBucket: 'medease-79081.appspot.com',
    androidClientId: '71986374792-eadmd8sjkh6amh9i7qr640t30akuqgfd.apps.googleusercontent.com',
    iosClientId: '71986374792-u3n3pm9kav4uun7766lgdptm6tk3ng5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.medeasee',
  );
}
